### PR TITLE
Getting the most recent save slot file name

### PR DESCRIPTION
**Pull request by astutejoe**
Hey rama, beforehand, I'd like for you to know that I very much appreciate your work. I was using your function to get all the save files and then found myself without one to get the most recent save file, so here it is, hope it suits the repository coding standards and, please, feel free to make or request modifications. 

Thanks! :)

### CODE REVIEW

**Comment by astutejoe** [comment]
By the way, I further developed it to remove the .sav extension when returning file names and made it so it also yields the file modified at time stamps so one could, for instance, display the save date-time alongside its name. Just let me know if that's desirable and I would make a pull request accordingly. Cheers! ;)

**Comment by astutejoe** [comment]
Hello again @EverNewJoy, I'm having to copy-paste my code to your plugin every time I have to update it. I'm not complaining but this code works perfectly and it's constantly used in my project, maybe it deserves some love? :)

Cheers and thanks!

**Comment by EverNewJoy** [comment]
Thank you so much for this!

Sorry about the delay in doing the merge :)

This is great! And very practical!

Victory to You @astutejoe !

♥

Rama

**Comment by astutejoe** [comment]
@EverNewJoy Hey @EverNewJoy ! I completely forgot to reply! I love that you liked it 😄 

My UE4 forum name is Gabriel Garcia with ID e22bf89a1cbd4966ad1c351b37833839

Cheers!! 🎉

**Pull request merged**
